export type Language = 'en' | 'hi';

export const translations = {
  en: {
    appName: "Dairy Smart AI",
    dashboard: "Dashboard",
    orders: "Orders",
    milk: "Milk Entry",
    production: "Production",
    more: "More",
    milkEntry: "Milk Entry",
    farmers: "Farmers",
    customers: "Customers",
    products: "Products",
    inventory: "Inventory",
    galla: "Galla / Cash",
    expenses: "Expenses",
    payments: "Payments",
    reports: "Reports",
    settings: "Settings",
    login: "Login",
    logout: "Logout",
    shift: "Shift",
    morning: "Morning",
    evening: "Evening",
    quantity: "Quantity (Ltr)",
    fat: "FAT (%)",
    snf: "SNF (%)",
    clr: "CLR",
    rate: "Rate (INR/Ltr)",
    amount: "Amount (INR)",
    submit: "Submit",
    loading: "Loading...",
    success: "Success",
    error: "Error",
    closeDay: "Close Day",
    expectedGalla: "Expected Galla",
    actualGalla: "Actual Galla",
    difference: "Difference",
    expectedProfit: "Expected Profit",
    actualProfit: "Actual Profit",
    todaySales: "Today's Sales",
    milkPurchased: "Milk Purchased",
    avgFat: "Avg FAT",
    avgSnf: "Avg SNF",
    language: "Language",
    hindi: "Hindi (हिंदी)",
    english: "English (अंग्रेज़ी)",
    quickActions: "Quick Actions",
    farmerId: "Farmer ID",
    name: "Name",
    mobile: "Mobile",
    village: "Village",
    addFarmer: "Add Farmer",
    saveFarmer: "Save Farmer",
    openingBalance: "Opening Balance",
    openingAdvance: "Opening Advance",
    actions: "Actions",
    viewLedger: "Ledger",
    viewMilk: "Milk History",
    milkType: "Milk Type",
    cow: "Cow",
    buffalo: "Buffalo",
    mixed: "Mixed",
    other: "Other"
  },
  hi: {
    appName: "डेयरी स्मार्ट AI",
    dashboard: "डैशबोर्ड",
    orders: "ऑर्डर्स",
    milk: "दूध एंट्री",
    production: "उत्पादन",
    more: "अन्य",
    milkEntry: "दूध प्रविष्टि",
    farmers: "किसान",
    customers: "ग्राहक",
    products: "उत्पाद",
    inventory: "स्टॉक",
    galla: "गल्ला",
    expenses: "खर्चे",
    payments: "भुगतान",
    reports: "रिपोर्ट्स",
    settings: "सेटिंग्स",
    login: "लॉगिन",
    logout: "लॉगआउट",
    shift: "शिफ्ट",
    morning: "सुबह",
    evening: "शाम",
    quantity: "मात्रा (लीटर)",
    fat: "फैट (%)",
    snf: "एसएनएफ (%)",
    clr: "सीएलआर",
    rate: "दर (₹/लीटर)",
    amount: "कुल राशि (₹)",
    submit: "सुरक्षित करें",
    loading: "लोड हो रहा है...",
    success: "सफलता",
    error: "त्रुटि",
    closeDay: "दिन बंद करें",
    expectedGalla: "अनुमानित गल्ला",
    actualGalla: "वास्तविक गल्ला",
    difference: "अंतर",
    expectedProfit: "अनुमानित लाभ",
    actualProfit: "वास्तविक लाभ",
    todaySales: "आज की बिक्री",
    milkPurchased: "खरीदा दूध",
    avgFat: "औसत फैट",
    avgSnf: "औसत SNF",
    language: "भाषा",
    hindi: "हिंदी",
    english: "अंग्रेज़ी",
    quickActions: "त्वरित कार्रवाई",
    farmerId: "किसान आईडी",
    name: "नाम",
    mobile: "मोबाइल",
    village: "गाँव",
    addFarmer: "किसान जोड़ें",
    saveFarmer: "किसान सुरक्षित करें",
    openingBalance: "प्रारंभिक शेष",
    openingAdvance: "प्रारंभिक अग्रिम",
    actions: "कार्रवाई",
    viewLedger: "खाता बही (लेजर)",
    viewMilk: "दूध इतिहास",
    milkType: "दूध का प्रकार",
    cow: "गाय",
    buffalo: "भैंस",
    mixed: "मिश्रित",
    other: "अन्य"
  }
};
